anthill:
  application:
    name: anthill-server
    version: 0.0.1-SNAPSHOT
  mongo:
    enabled: false
    type: single
  mail:
    account:
      - host: hwsmtp.exmail.qq.com
        port: 465
        user: project-dev@taotaozn.com
        pass: TAOtao0519@
        auth: true
        from: project-dev@taotaozn.com
        ssl-enable: true
        starttls-enable: true
        limit-count: 200
      - host: smtp.gmail.com
        port: 465
        user: taochenzn@gmail.com
        pass: uhvjsorhtnqmpish
        auth: true
        from: taochenzn@gmail.com
        ssl-enable: true
        starttls-enable: true
        limit-count: 100
  aliyun-oss-sts:
    enabled: true
    oss:
      primary:
        region-id: cn-shanghai
        access-key-id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        access-key-secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        role-arn: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        role-session-name: anthill-example
      cn-shanghai:
        region-id: cn-shanghai
        access-key-id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        access-key-secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        role-arn: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        role-session-name: anthill-example
  web:
    xss:
      enabled: false
    auth:
      excludes:
        - /
        # 静态资源
        - /*.html
        - /**/*.html
        - /**/*.css
        - /**/*.js
        # 公共路径
        - /favicon.ico
        # swagger 文档配置
        - /*/api-docs
        - /*/api-docs/**
        # actuator 监控配置
        - /actuator
        - /actuator/**
  swagger:
    title: ${anthill.application.name}
    version: ${anthill.application.version}
    description: ${anthill.application.version}
    contact:
      name: chriswoodcn
      email: chriswoodcn@aliyun.com

mybatis-flex:
  datasource:
    ds1:
      type: hikari
      url: jdbc:mysql://192.168.2.188:3307/anthill_example_jpa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: rootroot
    ds2:
      type: hikari
      url: jdbc:mysql://192.168.2.188:3307/anthill_example_jpa_slave?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: rootroot

logging:
  level:
    cn.chriswood.anthill.infrastructure: debug
    org.springframework.data.jpa: debug
  config: classpath:logback-spring.xml
  charset:
    file: UTF-8
server:
  port: 8080
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  #    fix sa-token SpringBoot 3.x 路由拦截鉴权报错
  #    No more pattern data allowed after {*...} or ** pattern element
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      repositories:
        enabled: false
      # 地址
      host: localhost
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 2
      # 密码(如没有密码请注释掉)
      password: 123456
      # 连接超时时间
      timeout: 10s
      # 是否开启ssl
      ssl.enabled: false
    mongodb:
      uri: mongodb://admin:admin123456@192.168.2.188:27018/test?authSource=admin

springdoc:
  #  default-flat-param-object: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: basic
      display-name: basic
      packages-to-scan:
        - cn.chriswood.anthill.example.flex.modules.basic
    - group: demo
      display-name: demo
      packages-to-scan:
        - cn.chriswood.anthill.example.flex.modules.demo
